x1=rnorm(100)
x2=rnorm(100)
x3=rnorm(100)
t = data.frame(a = x1,b = x1+x2, c = x1+x2+x3)
##plot(x1, main=c("Mean=", mean(x1)))
##plot(t$a, main=c("SD=", sd(t$a), "Mean=", mean(t$a)))
##plot(x2, main=c("Mean=", mean(x2)))
##plot(t$b, main=c("SD=", sd(t$b), "Mean=", mean(t$b)))
##plot(x3, main=c("Mean=", mean(x3)))
##plot(t$c, main=c("SD=", sd(t$c), "Mean=", mean(t$c)))
##This section plots all 3 over each other in one plot
plot(t$a, type="l", ylim=range(t),lwd=3, col=rgb(1,0,0,0.3))
lines(t$b, type="s", lwd=2,col=rgb(0.3,0.4,0.3,0.9))
points(t$c, pch=20, cex=2,col=rgb(0,1,1,0.3))
z=data.frame(x1,x2,x3)
write.table(row.names=FALSE)
